// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_GetAssetPrice_FullMethodName       = "/service.AssetService/GetAssetPrice"
	AssetService_AddAssetToWatchlist_FullMethodName = "/service.AssetService/AddAssetToWatchlist"
	AssetService_GetWatchlist_FullMethodName        = "/service.AssetService/GetWatchlist"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// O Serviço Principal
type AssetServiceClient interface {
	// GET /api/assets/{symbol}
	GetAssetPrice(ctx context.Context, in *AssetRequest, opts ...grpc.CallOption) (*AssetPriceResponse, error)
	// POST /api/assets/watchlist/{symbol}
	AddAssetToWatchlist(ctx context.Context, in *AssetRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	//GET /api/assets/watchlist
	GetWatchlist(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WatchlistResponse, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) GetAssetPrice(ctx context.Context, in *AssetRequest, opts ...grpc.CallOption) (*AssetPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetPriceResponse)
	err := c.cc.Invoke(ctx, AssetService_GetAssetPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) AddAssetToWatchlist(ctx context.Context, in *AssetRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, AssetService_AddAssetToWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetWatchlist(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WatchlistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchlistResponse)
	err := c.cc.Invoke(ctx, AssetService_GetWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
//
// O Serviço Principal
type AssetServiceServer interface {
	// GET /api/assets/{symbol}
	GetAssetPrice(context.Context, *AssetRequest) (*AssetPriceResponse, error)
	// POST /api/assets/watchlist/{symbol}
	AddAssetToWatchlist(context.Context, *AssetRequest) (*SuccessResponse, error)
	//GET /api/assets/watchlist
	GetWatchlist(context.Context, *Empty) (*WatchlistResponse, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) GetAssetPrice(context.Context, *AssetRequest) (*AssetPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetPrice not implemented")
}
func (UnimplementedAssetServiceServer) AddAssetToWatchlist(context.Context, *AssetRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAssetToWatchlist not implemented")
}
func (UnimplementedAssetServiceServer) GetWatchlist(context.Context, *Empty) (*WatchlistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWatchlist not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_GetAssetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetAssetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetAssetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetAssetPrice(ctx, req.(*AssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_AddAssetToWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).AddAssetToWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_AddAssetToWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).AddAssetToWatchlist(ctx, req.(*AssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetWatchlist(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssetPrice",
			Handler:    _AssetService_GetAssetPrice_Handler,
		},
		{
			MethodName: "AddAssetToWatchlist",
			Handler:    _AssetService_AddAssetToWatchlist_Handler,
		},
		{
			MethodName: "GetWatchlist",
			Handler:    _AssetService_GetWatchlist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
